// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPThHwI0MWxwrcuu_lDzGYSI9s7rGerHc',
    appId: '1:207983039731:web:c0e9a58c05429cd245d386',
    messagingSenderId: '207983039731',
    projectId: 'clearledger-8b71c',
    authDomain: 'clearledger-8b71c.firebaseapp.com',
    storageBucket: 'clearledger-8b71c.firebasestorage.app',
    measurementId: 'G-PR0GDGMXJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQT6dF5awe8KC9dZD70faSYaJy1Y6TDsM',
    appId: '1:207983039731:android:8fec95576dd8c98845d386',
    messagingSenderId: '207983039731',
    projectId: 'clearledger-8b71c',
    storageBucket: 'clearledger-8b71c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMbphuqDP25H-Y8JMAWDQWEO-SkknVPmM',
    appId: '1:207983039731:ios:8970b5231fbf21ea45d386',
    messagingSenderId: '207983039731',
    projectId: 'clearledger-8b71c',
    storageBucket: 'clearledger-8b71c.firebasestorage.app',
    iosBundleId: 'com.example.clearLedger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMbphuqDP25H-Y8JMAWDQWEO-SkknVPmM',
    appId: '1:207983039731:ios:8970b5231fbf21ea45d386',
    messagingSenderId: '207983039731',
    projectId: 'clearledger-8b71c',
    storageBucket: 'clearledger-8b71c.firebasestorage.app',
    iosBundleId: 'com.example.clearLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPThHwI0MWxwrcuu_lDzGYSI9s7rGerHc',
    appId: '1:207983039731:web:f08375ce1d20e58345d386',
    messagingSenderId: '207983039731',
    projectId: 'clearledger-8b71c',
    authDomain: 'clearledger-8b71c.firebaseapp.com',
    storageBucket: 'clearledger-8b71c.firebasestorage.app',
    measurementId: 'G-QC162L1MEZ',
  );
}
